# Generated by Django 4.2.7 on 2023-11-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rollnumber',
            field=models.IntegerField(default=103),
            preserve_default=False,
        ),
    ]
